#endpoint url
@url = http://localhost:6051
# base64 encoded admin:password
@basicAuth = YWRtaW46Zm9vYmFy

### convert guid to steamid
GET {{url}}/939f64acae081b9deeed3fef7be87b57

### convert steamid to guid
GET {{url}}/76561197970265730

### multi request steamid and guid
POST {{url}}
Content-Type: application/json

[
  "0cc99e3ab77a8a2037d278816f3c9ca7",
  "f79984b78ebed3536ed45be4ec03018b",
  "76561197960265763"
]

### admin page
GET {{url}}/admin
Authorization: Basic {{basicAuth}}

### admin stats page
GET {{url}}/admin/status
Authorization: Basic {{basicAuth}}

### generate more ids
POST {{url}}/admin/generate
Content-Type: application/json
Authorization: Basic {{basicAuth}}

{ "till": "100000" }