webserver:
  #webserver listenport
  port: 6051
  #headers to add to the api
  #headers will only be appended to the public endpoints
  #and not to the admin interface
  headers:
    Access-Control-Allow-Origin: "*"
  #maximum keys to request at once
  postKeyLimit: 250
  #disable admin page access completely
  #you cann access the admin page via the url "/admin"
  disableAdmin: false
  #use basic auth for all endpoints
  forceBasicAuthEverywhere: false
  #basic auth access credentials
  #request headers will need:
  #Authorization: Basic [BASE64ENCODE("username:password")]
  credentials:
    admin: "CHANGE ME!!!"
data:
  #folder to save data to
  dir: ./data
  cache:
    #time to keep data in cache in ms (14 days)
    keepTime: 1008000000
    #time till cache gets saved to cache (1 hour)
    saveInterval: 3600000
mysql:
  #for all connection options please see https://github.com/mysqljs/mysql#connection-options
  connection:
    #mysql database hostname
    host: "localhost"
    #mysql database port
    port: 3306
    #mysql database
    database: "beguid"
    #mysql database username
    user: ""
    #mysql database password
    password: ""
    #mysql maximum connection for the pool
    connectionLimit: 16
  #database table prefix to use
  table: "beguid_"
converter:
  #how many inserts should be done at once when generating ids
  insertBatchSize: 20000
  #this defines how much bytes of the guid will be saved
  #it is recommended to use either 3 or 4
  #byteLength of 3: needs 17.6GB Disk Space per billion ids -> uses more CPU per request (but barely noticeable)
  #byteLength of 4: needs 19.6GB Disk Space per billion ids -> requires less CPU per request
  byteLength: 3
  #initial steamid should not be changed
  #leave it as a string
  offset: "76561197960265730"